apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-backend
  namespace: multi-cloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-backend
  template:
    metadata:
      labels:
        app: nginx-backend
    spec:
      containers:
        - name: backend
          #image: gcr.io/multi-cloud-platform/nginx-backend:v1.0.0
          # IMAGE_NAME and IMAGE_TAG are defined in configMap
          image: "$(IMAGE_NAME):$(IMAGE_TAG)"
          ports:
            - containerPort: 5000
            #- containerPort: $(BACKEND_PORT)
          env:
            - name: SQLALCHEMY_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: gcp-secrets
                  key: DATABASE_URI
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gcp-secrets
                  key: JWT_SECRET_KEY
          volumeMounts:
            - name: gcp-secrets-store
              mountPath: /mnt/secrets
              readOnly: true
      volumes:
        - name: gcp-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: gcp-secrets
